// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

package frc.robot.commands;

import java.util.List;

import edu.wpi.first.math.kinematics.ChassisSpeeds;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;
import edu.wpi.first.wpilibj2.command.CommandBase;
import frc.robot.Util;
import frc.robot.commands.paths.CommandPathPiece;
import frc.robot.subsystems.Barrel;
import frc.robot.subsystems.Drivetrain;
import frc.robot.subsystems.PixyObject;

/**
 *
 */
public class RawBarrelForTime extends CommandBase implements CommandPathPiece{


    long timeout = 0;
    long timeToStop = 0;
    Barrel barrel;
    double power;
    /**
     * It will go field-oriented
     * @param drivetrain
     * @param xSpeed
     * @param ySpeed
     */
    public RawBarrelForTime(Barrel barrel, double power, long timeout) {

        this.power = power;
        this.timeout=timeout;
        this.barrel= barrel;

    }
    
    @Override
    public void initialize() {
        timeToStop = System.currentTimeMillis()+timeout;

    }


    
    // Called repeatedly when this Command is scheduled to run
    @Override
    public void execute() {
        barrel.autoBarrel = false;
        barrel.rawScrew(power);
        
    }

    // Make this return true when this Command no longer needs to run execute()
    @Override
    public boolean isFinished() {

        return System.currentTimeMillis()>timeToStop;
    }

    @Override
    public void end(boolean interrupted) {
        barrel.rawScrew(0);
    }
    
    @Override
    public double getRequestedStartSpeed() {
        return 1;
    }

}
