// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

package frc.robot.commands;

import edu.wpi.first.wpilibj2.command.CommandBase;
import frc.robot.commands.paths.CommandPathPiece;

/**
 *
 */
public class WaitTime extends CommandBase implements CommandPathPiece{


    long timeout = 0;
    long timeToStop = 0;
    
    public WaitTime(long timeout) {
        this.timeout = timeout;
    }
    
    @Override
    public void initialize() {
        timeToStop = System.currentTimeMillis()+timeout;
    }
    
    // Called repeatedly when this Command is scheduled to run
    @Override
    public void execute() {

    }

    // Make this return true when this Command no longer needs to run execute()
    @Override
    public boolean isFinished() {

        return System.currentTimeMillis()>timeToStop;
    }

}
